# true = feature enabled
# false = feature disabled
# 1.00 = 100% drop chance, 0.50 = 50% drop chance (a drop chance from 0.01-0.05 is recommended)
spawnerShards: true
enchantShards: true
sendEnchantMessage: false
sendSpawnerMessage: false
mobSpawnerShards:
  rabbit: true
  rabbitpercent: 0.20
  chicken: true
  chickenpercent: 0.15
  cow: true
  cowpercent: 0.10
  spider: true
  spiderpercent: 0.08
  zombie: true
  zombiepercent: 0.08
  skeleton: true
  skeletonpercent: 0.08