name: emptySkyUtils
version: '${project.version}'
main: com.empty.emptyskyutils.EmptySkyUtils
api-version: '1.21'
description: 'A plugin that provides various rewards and utility items for Skyblock styled servers.'
author: 'empty'
commands:
  emptyskyutils:
    description: 'Main command for EmptySkyUtils'
    usage: '/<command> [subcommand] [arguments]'
    aliases: [esu, skyutils]
  origin:
    description: 'Open the origin selection menu'
    usage: '/<command>'
permissions:
  emptyskyutils.admin:
    description: 'Allows the user to access admin commands'
    default: op

