name: emptySkyUtils
version: '${project.version}'
main: com.empty.emptyskyutils.EmptySkyUtils
api-version: '1.21'
commands:
  emptySkyUtilsreload:
    description: reloads the config
    usage: /<command>
    aliases: [skyreload ,skyutilsreload]
  emptySkyUtils:
    aliases: [ esu ,skyutils ]
  giveshards:
